### ISSUE TITLE
No icons in Android app

### ISSUE THREAD

**Issue by Fxsch** [beecho01/material-symbols#1]
**Describe the bug**
The icons aren't being displayed in the Android Home Assistant app, there's just nothing instead

**To Reproduce**
1. Use these icons
2. Open Home Assistant app on Android

**Expected behavior**
The icons should be there, like when using Home Assistant through the browser

**Smartphone (please complete the following information):**
 - Device: Nothing Phone 1
 - OS: Android 13
 - Version: (Version of what?)

**Comment by beecho01** [comment]
Hi @Fxsch, you'll have to excuse me whist I work through this. Not a strong coder, so will do my best to help.
Its a substantially larger number of lines to load compared to related repositories (of which I took inspiration).

I can see there was as similar issue in @arallsopp's Home Assistant Community [Thread ](https://community.home-assistant.io/t/created-custom-colorizable-hue-icons-as-a-lovelace-resource/321110/78) relating to his repository that sounds similar.

Could you try the step in the above thread and clear the app cache and see if this helps?

If not, I'll see if I can optimise what I have done so far or identify the root cause.

**Comment by beecho01** [comment]
@Fxsch Are you still having the issue? Has this resolved your issue?

**Comment by Fxsch** [comment]
This issue has been resolved at some point, yes. Sorry, I forgot about this issue and just used the default icons but it's great that I can use these icons as well now.
